version: 0.0
os: linux
files:
  - source: 00010358
    destination: /var/www
  - source: deploy-scripts/webapi.service
    destination: /etc/systemd/system
hooks:
  ApplicationStop:
    - location: deploy-scripts/stop-install.sh
      timeout: 180
  BeforeInstall:
    - location: deploy-scripts/before-install.sh
      timeout: 180
  ApplicationStart:
    - location: deploy-scripts/start-install.sh
      timeout: 180